### ISSUE TITLE
Step 8: Define which property to use for SWHID in DC

### ISSUE THREAD

**Issue by hjonin** [SoFairOA/documentation#16]
> Morane: Which property should be used
>
> Matteo: The standard Dublin Core doesn't have any indication of this. However  the two most common extension should be able to cover this case with datacite:relatedIdentifier (for OpenAIRE) and dc:relation or rioxx:ext_relation and [https://rioxx.net/profiles/#dc:relation](https://www.google.com/url?q=https://rioxx.net/profiles/%23dc:relation&sa=D&source=docs&ust=1723531627149663&usg=AOvVaw3B1c6jkybll7CG70ydFgNc)
>
> I think we need to look into it a bit more and probably define internally what is the recommended way for exposing this, I'll prepare some examples so we can see how it looks
>
> Morane: Could you add these options in text directly? we will refine for 2nd iteration.
>
> Matteo: Yes, but I thought that HAL should have a ready made example for this? How does HAL includes SWID in the metadata? In any case, added my suggestions and examples. The examples assume that SWHID are URLs, in this way, we are still compliant to the metadata guidelines. If the SWHID is not a URL we will need to require some extensions to the application profiles to be fully compliant.
>
> Morane: That's a good point. I'll look into HAL, but here the docs is higher level and might be a basis for a recommendations for multiple OAs. A SWHID can be a permalink, thus a URL

**Comment by mcancellieri** [comment]
@moranegg do you have any progress? How is HAL exposing the SWHID in the metadata? And if there is no answer, is there any recommendation?

**Comment by moranegg** [comment]
SWHID is not exposed in DC:
https://hal.science/hal-04335677v1/dcterms

It is exposed in TEI format and in CodeMeta terms:
https://hal.science/hal-04335677v1/tei

@mcancellieri

**Comment by mcancellieri** [comment]
I think as one of the outputs of T3.2 and also as an input for T6.1 we would like to see the SWHID mentions exposed in the repository metadata. Even if it doesn't happen immediately it's probably something we should discuss how it should look like. What do you think?

**Comment by mcancellieri** [comment]
I think this should be closed by #30
