### ISSUE TITLE
Step 9: OA is confusing (definition clash)

### ISSUE THREAD

**Issue by mcancellieri** [SoFairOA/documentation#21]
The term OA is used to define research repositories. It is probably used to disambiguate between code repositories and research paper repositories. I suggest we use a different term/acronym because, from our community, OA means Open Access in the context of licensing and makes reading confusing. 
Can we switch it to "Research Repository" (RR) or "Institutional Repositories" (IR)?

This is a minor issue. There is nothing wrong with Open Access Repository as a definition, the issue is when used as an acronym in the documentation or when we speak.

**Comment by moranegg** [comment]
Sure. Go ahead!

The Acronym OA was used in the submitted proposal [diagram](https://sofairoa.github.io/documentation/02-introduction/) and was reused in documenting the workflow.
We can use IR if that makes this clearer for you.

**Comment by mcancellieri** [comment]
Yes, what I mean is when we use OA on its own. When is used as "OA Repository" there is nothing wrong, my issue is when is called just "OA" without the repository next to it, it's when it reads strange to me. For example in the title of Step 9

**Comment by moranegg** [comment]
Got you. so the fix is easier, let's add repository after OA when it is missing.
